package lesson3;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Lesson1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void empty1() {
    driver.get("https://crm.geekbrains.space/user/login");
    driver.manage().window().setSize(new Dimension(1024, 768));
    driver.findElement(By.id("prependedInput")).sendKeys("Applanatest");
    driver.findElement(By.id("prependedInput2")).sendKeys("Student2020!");
    driver.findElement(By.id("_submit")).click();
    assertThat(driver.getTitle(), is("Панель инструментов"));
    {
      WebElement element = driver.findElement(By.linkText("Проекты"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Мои проекты")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//title[text()=\'Все - Мои проекты - Все проекты - Проекты\']")));
    }
    assertThat(driver.getTitle(), is("Все - Мои проекты - Все проекты - Проекты"));
    {
      List<WebElement> elements = driver.findElements(By.xpath("//a[@title=\'Создать проект\']"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.linkText("Создать проект")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//title[text()=\'Создать проект - Все проекты - Проекты\']")));
    }
    assertThat(driver.getTitle(), is("Создать проект - Все проекты - Проекты"));
    driver.findElement(By.xpath("//input[@name=\'crm_project[name]\']")).click();
    driver.findElement(By.xpath("//input[@name=\'crm_project[name]\']")).sendKeys("000001");
    driver.findElement(By.xpath("//a[@class=\'select2-choice select2-default\']/span[@class=\'select2-arrow\']")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//div[text()=\'«Все организации»\']")));
    }
    driver.findElement(By.xpath("//*[@id=\"select2-drop\"]/div/input")).sendKeys("1234");
    driver.findElement(By.xpath("//div [@class=\'select2-result-label\']//span[text()=\'1234\']")).click();
    driver.findElement(By.xpath("//div[@class=\'select2-container select2\']/a")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//div[text()=\'Familiy Imy\']")));
    }
    driver.findElement(By.xpath("//div[text()=\'Familiy Imy\']")).click();
    {
      WebElement dropdown = driver.findElement(By.xpath("//select[@name=\'crm_project[businessUnit]\']"));
      dropdown.findElement(By.xpath("//option[. = 'Research & Development']")).click();
    }
    {
      WebElement dropdown = driver.findElement(By.xpath("//select[@name=\'crm_project[curator]\']"));
      dropdown.findElement(By.xpath("//option[. = 'Applanatest Applanatest Applanatest']")).click();
    }
    {
      WebElement dropdown = driver.findElement(By.xpath("//select[@name=\'crm_project[rp]\']"));
      dropdown.findElement(By.xpath("//option[. = 'Applanatest Applanatest Applanatest']")).click();
    }
    {
      WebElement dropdown = driver.findElement(By.xpath("//select[@name=\'crm_project[administrator]\']"));
      dropdown.findElement(By.xpath("//option[. = 'Applanatest Applanatest Applanatest']")).click();
    }
    {
      WebElement dropdown = driver.findElement(By.xpath("//select[@name=\'crm_project[manager]\']"));
      dropdown.findElement(By.xpath("//option[. = 'Applanatest Applanatest Applanatest']")).click();
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//span[text()=\'1234\']"));
      assert(elements.size() > 0);
    }
    {
      String value = driver.findElement(By.xpath("//select[@name=\'crm_project[businessUnit]\']")).getAttribute("value");
      assertThat(value, is("1"));
    }
    {
      String value = driver.findElement(By.xpath("//select[@name=\'crm_project[curator]\']")).getAttribute("value");
      assertThat(value, is("115"));
    }
    {
      String value = driver.findElement(By.xpath("//select[@name=\'crm_project[rp]\']")).getAttribute("value");
      assertThat(value, is("115"));
    }
    {
      String value = driver.findElement(By.xpath("//select[@name=\'crm_project[administrator]\']")).getAttribute("value");
      assertThat(value, is("115"));
    }
    {
      String value = driver.findElement(By.xpath("//select[@name=\'crm_project[manager]\']")).getAttribute("value");
      assertThat(value, is("115"));
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//span[text()=\'Familiy Imy\']"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.xpath("//button[@class=\'btn btn-success action-button\']")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".filter-box")));
    }
    assertThat(driver.getTitle(), is("Все - Проекты - Все проекты - Проекты"));
  }
  @Test
  public void empty2() {
    driver.get("https://crm.geekbrains.space/user/login");
    driver.manage().window().setSize(new Dimension(1024, 768));
    driver.findElement(By.id("prependedInput")).sendKeys("Applanatest");
    driver.findElement(By.id("prependedInput2")).sendKeys("Student2020!");
    driver.findElement(By.id("_submit")).click();
    assertThat(driver.getTitle(), is("Панель инструментов"));
    {
      WebElement element = driver.findElement(By.xpath("//a/span[text()=\'Контрагенты\']"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.xpath("//span[text()=\'Контактные лица\']/parent::a")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//title[text()=\'Все - Контактные лица - Контактные лица - Контрагенты\']")));
    }
    assertThat(driver.getTitle(), is("Все - Контактные лица - Контактные лица - Контрагенты"));
    {
      List<WebElement> elements = driver.findElements(By.xpath("//tbody[@class=\'grid-body\']"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//a[@title=\'Создать контактное лицо\']"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.xpath("//a[@title=\'Создать контактное лицо\']")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//title[text()=\'Создать контактное лицо - Контактные лица - Контрагенты\']")));
    }
    assertThat(driver.getTitle(), is("Создать контактное лицо - Контактные лица - Контрагенты"));
    driver.findElement(By.xpath("//input[@name=\'crm_contact[lastName]\']")).sendKeys("Домашкова");
    {
      String value = driver.findElement(By.xpath("//input[@name=\'crm_contact[lastName]\']")).getAttribute("value");
      assertThat(value, is("Домашкова"));
    }
    driver.findElement(By.xpath("//input[@name=\'crm_contact[firstName]\']")).sendKeys("Домашка");
    {
      String value = driver.findElement(By.xpath("//input[@name=\'crm_contact[firstName]\']")).getAttribute("value");
      assertThat(value, is("Домашка"));
    }
    driver.findElement(By.xpath("//span[text()=\'Укажите организацию\']/parent::a")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//div[text()=\'1234\']")));
    }
    driver.findElement(By.xpath("//div[@id=\'select2-drop\']//li/div[text()=\'Bins-Haley\']")).click();
    assertThat(driver.findElement(By.xpath("//span[text()=\'Bins-Haley\']")).getText(), is("Bins-Haley"));
    driver.findElement(By.xpath("//input[@name=\'crm_contact[jobTitle]\']")).sendKeys("Преподаватель");
    {
      String value = driver.findElement(By.xpath("//input[@name=\'crm_contact[jobTitle]\']")).getAttribute("value");
      assertThat(value, is("Преподаватель"));
    }
    driver.findElement(By.xpath("//button[@class=\'btn btn-success action-button\']")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//title[text()=\'Все - Контактные лица - Контактные лица - Контрагенты\']")));
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[@class=\'flash-messages-frame\']//div[text()=\'Контактное лицо сохранено\']"));
      assert(elements.size() > 0);
    }
  }
}
